channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - numpy=1.18.1
  - scikit-image=0.17.2
  - urllib3=1.25.9
  - json-c=0.13.1
  - requests=2.23.0
  - flask=1.1.2
  - matplotlib=3.1.3
  - pandas=1.0.3
  - scipy=1.4.1
  - pip=20.0.2
  - scikit-learn=0.22.1
  - openpyxl=3.0.3
  - notebook
  - albumentations=0.4.6
  - pip:
    - keras==2.4.0
    - keras_applications==1.0.8
    - image-classifiers==1.0.0
    - efficientnet==1.0.0
    - segmentation_models==1.0.1
    - descartes==1.1.0
    - fiona==1.8.17
    - tqdm==4.50.1